### ISSUE TITLE
7 - Hangman (misc)

### ISSUE THREAD

**Issue by yudori** [ebosetalee/20-days-challenge#20]
We'll take the day to make sure you understand what you've written to a good extent. Otherwise, it may feel much harder moving forward. 

This is important.

- Read to understand what each line in your code does.
- This is your chance to do further readings around the topics you've encountered so far that you may not completely understand. This is a good resource that you can choose to use https://www.w3schools.com/python/
- With your new knowledge, Identify parts of the hangman code that you can improve and push something to that effect.
- Flex 😄 

Feel free to reach out if you have questions.

**Comment by jirevwe** [comment]
@ebosetalee how far? Not seen anything yet

**Comment by ebosetalee** [comment]
I intend to use classes 
But I don't understand it well yet @jirevwe

**Comment by jirevwe** [comment]
Oh ok
